"""Add width column to boat_slip

Revision ID: 6ce1b4bbae8a
Revises: 2d90ca00d82d
Create Date: 2025-01-12 17:28:10.456162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce1b4bbae8a'
down_revision = '2d90ca00d82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_slip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('annual_taxes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('annual_hoa_fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contact_info', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('live', sa.Boolean(), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_slip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.drop_column('live')
        batch_op.drop_column('contact_info')
        batch_op.drop_column('annual_hoa_fees')
        batch_op.drop_column('annual_taxes')
        batch_op.drop_column('length')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
